name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Cypress:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Cypress tests
        run: make test
  CodeQL:
    runs-on: ubuntu-latest
  
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go, javascript
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Compile
        run: make build
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
