name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.26.0/tinygo_0.26.0_amd64.deb
          sudo dpkg -i tinygo_0.26.0_amd64.deb

      - name: Build
        run: make build

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          vercel build static --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy Project Artifacts to Vercel
        run: | 
          npx wait-on file:.vercel/output/static && \
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
